name: Hello world

author: Ugur Ozgen

description: Dummy description

inputs:
    who-to-greet:
        description: "Who to greet"
        required: true
        default: Ugur

outputs:
    time:
        description: "The greeting time"

runs:
    using: "docker"
    image: "Dockerfile"
    # entrypoint:
    args:
        - ${{ inputs.who-to-greet }}
